2019-10-30 23:31:01,637	INFO	main1	<module>	Line:11	app started
2019-10-30 23:31:01,649	WARNING	_internal	_log	Line:122	 * Debugger is active!
2019-10-30 23:31:01,674	INFO	_internal	_log	Line:122	 * Debugger PIN: 185-856-785
2019-10-30 23:31:01,688	INFO	_internal	_log	Line:122	 * Running on http://192.168.2.210:9100/ (Press CTRL+C to quit)
2019-10-30 23:31:09,738	INFO	_internal	_log	Line:122	192.168.2.210 - - [30/Oct/2019 23:31:09] "GET /ProblemSet/init/cf4e7e3c-5067-4a6a-8d38-8e05087eb54d/ww HTTP/1.1" 200 -
2019-10-30 23:31:09,751	INFO	_internal	_log	Line:122	192.168.2.210 - - [30/Oct/2019 23:31:09] "GET /ProblemSet/answer/cf4e7e3c-5067-4a6a-8d38-8e05087eb54d/3 HTTP/1.1" 200 -
2019-10-30 23:31:12,599	INFO	_internal	_log	Line:122	192.168.2.210 - - [30/Oct/2019 23:31:12] "GET /ProblemSet/init/cf4e7e3c-5067-4a6a-8d38-8e05087eb54d/ww HTTP/1.1" 200 -
2019-10-30 23:31:12,806	INFO	_internal	_log	Line:122	192.168.2.210 - - [30/Oct/2019 23:31:12] "GET /ProblemSet/answer/cf4e7e3c-5067-4a6a-8d38-8e05087eb54d/2 HTTP/1.1" 200 -
2019-10-30 23:32:35,017	INFO	_internal	_log	Line:122	 * Detected change in 'C:\\development\\examsystem\\services\\daos\\problemsetDAO.py', reloading
